TRI_LAYER_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_LED_COUNT = 70  # Cantidad total de LEDs
RGB_MATRIX_KEYPRESSES = yes  # Efecto por tecla presionada
